name: Build
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      mutation-testing: false
      sonarqube: false
