name: Lock resolved issues and PRs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:
jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          pr-inactive-days: '30'